---
title: "App reference details"
output: html_document
---

Please see the article below or contact the authors for app details:


[**Modelling direct and herd protection effects of vaccination against the SARS‐CoV‐2 Delta variant in Australia**](https://www.mja.com.au/journal/2021/215/9/modelling-direct-and-herd-protection-effects-vaccination-against-sars-cov-2)

Emma S McBryde, Michael T Meehan, Jamie M Caldwell, Adeshina I Adekunle, Samson T Ogunlade, MD Abdul Kuddus, Romain Ragonnet, Pavithra Jayasundara, James M Trauer and Robert C Cope. 
*Med J Aust* 2021; 215 (9): 427-432. || doi: 10.5694/mja2.51263

Source code and data implementing the methods used here is available at:
https://github.com/michaeltmeehan/covid19/tree/main/immunization_australia

Please note that confidence intervals around vaccine efficacy are only available for the Pfizer and AstraZeneca vaccines due to the amount of literature available.

Where public health measures are anticipated to reduce transmission, the resulting R_eff should be used in the place of R_0 in this tool. 


### Disclaimer

The team that authored this app, and the organisations that employ them, accept no responsibility for the results of any actions taken on the basis of information on this website, nor for the accuracy or completeness of any material contained herein. 

Please note this app may discontinue or vary at any time without notice.

This website contains links to external organisations and information. The team that authored this app, and the organisations that employ them, do not accept responsibility for, nor endorse, the content of any linked site.